language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_script:
  - npm i mocha rollup -g
install:
  - npm install
before_script:
  - npm run build
branches:
  only:
  - master